<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.2.0" />
    <PackageReference Include="Google.GenAI" Version="1.14.0" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.8" />
    <PackageReference Include="PdfPig" Version="0.1.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AIKnowledgeBot.InterFace\AIKnowledgeBot.InterFace.csproj" />
  </ItemGroup>

</Project>
